### ISSUE TITLE
Misleading error when using European endpoints

### ISSUE THREAD

**Issue by miroag** [logzio/cloudwatch-logs-shipper-lambda#14]
Being from Europe, I've used the https://listener-eu.logz.io:8071 endpoint
With surprising error result 401: Logging token is not valid

Either both endpoints needs to be synced on tokens or if European endpoint is not valid, documentation needs to be updated.

**Comment by idohalevi** [comment]
@miroag The listener URL depends on the account not on when you're from. Can you please log to the app and check if you see 'app.logz.io' as part of the URL? If so your account is not in the EU.

**Comment by miroag** [comment]
@idohalevi Yes, it's app.logz.io. 
a) It shall be in Europe, as I registered in Europe. I guess this is a fault from registration process. 
b) The error is misleading. As a potential customer of logz.io I shall not spend a day figuring out why my token is invalid.

**Comment by idohalevi** [comment]
@miroag
a) The account is by default in the US. If you want it to be in EU please contact your salesperson. In general, under the log shipping page, you can find all the shipping methods with your URL and token included in it.
b) As you can see we answer quick, feel free to contact us here or on support if you have any issues.
